<?php

namespace App\Http\Controllers;

class EmojiController extends Controller
{
    public function index()
    {
        $json = <<<'JSON'
{
    "grinning": {
        "unicode": "1f600",
        "unicode_alt": "",
        "code_decimal": "&#128512;",
        "name": "grinning face",
        "shortname": ":grinning:",
        "channel": "people",
        "emoji_order": "1",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "smiley", "emotion"]
    },
    "grin": {
        "unicode": "1f601",
        "unicode_alt": "",
        "code_decimal": "&#128513;",
        "name": "grinning face with smiling eyes",
        "shortname": ":grin:",
        "channel": "people",
        "emoji_order": "2",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "silly", "smiley", "emotion", "good", "selfie"]
    },
    "joy": {
        "unicode": "1f602",
        "unicode_alt": "",
        "code_decimal": "&#128514;",
        "name": "face with tears of joy",
        "shortname": ":joy:",
        "channel": "people",
        "emoji_order": "3",
        "aliases": [],
        "aliases_ascii": [":')", ":'-)"],
        "keywords": [
            "happy",
            "silly",
            "smiley",
            "cry",
            "laugh",
            "emotion",
            "sarcastic"
        ]
    },
    "rofl": {
        "unicode": "1f923",
        "unicode_alt": "",
        "code_decimal": "&#129315;",
        "name": "rolling on the floor laughing",
        "shortname": ":rofl:",
        "channel": "people",
        "emoji_order": "4",
        "aliases": [":rolling_on_the_floor_laughing:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "smiley": {
        "unicode": "1f603",
        "unicode_alt": "",
        "code_decimal": "&#128515;",
        "name": "smiling face with open mouth",
        "shortname": ":smiley:",
        "channel": "people",
        "emoji_order": "5",
        "aliases": [],
        "aliases_ascii": [":D", ":-D", "=D"],
        "keywords": ["happy", "smiley", "emotion", "good"]
    },
    "smile": {
        "unicode": "1f604",
        "unicode_alt": "",
        "code_decimal": "&#128516;",
        "name": "smiling face with open mouth and smiling eyes",
        "shortname": ":smile:",
        "channel": "people",
        "emoji_order": "6",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "smiley", "emotion"]
    },
    "sweat_smile": {
        "unicode": "1f605",
        "unicode_alt": "",
        "code_decimal": "&#128517;",
        "name": "smiling face with open mouth and cold sweat",
        "shortname": ":sweat_smile:",
        "channel": "people",
        "emoji_order": "7",
        "aliases": [],
        "aliases_ascii": ["':)", "':-)", "'=)", "':D", "':-D", "'=D"],
        "keywords": ["smiley", "workout", "sweat", "emotion"]
    },
    "laughing": {
        "unicode": "1f606",
        "unicode_alt": "",
        "code_decimal": "&#128518;",
        "name": "smiling face with open mouth and tightly-closed eyes",
        "shortname": ":laughing:",
        "channel": "people",
        "emoji_order": "8",
        "aliases": [":satisfied:"],
        "aliases_ascii": [">:)", ">;)", ">:-)", ">=)"],
        "keywords": ["happy", "smiley", "laugh", "emotion"]
    },
    "wink": {
        "unicode": "1f609",
        "unicode_alt": "",
        "code_decimal": "&#128521;",
        "name": "winking face",
        "shortname": ":wink:",
        "channel": "people",
        "emoji_order": "9",
        "aliases": [],
        "aliases_ascii": [";)", ";-)", "*-)", "*)", ";-]", ";]", ";D", ";^)"],
        "keywords": ["silly", "smiley", "emotion"]
    },
    "blush": {
        "unicode": "1f60a",
        "unicode_alt": "",
        "code_decimal": "&#128522;",
        "name": "smiling face with smiling eyes",
        "shortname": ":blush:",
        "channel": "people",
        "emoji_order": "10",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "smiley", "emotion", "good", "beautiful"]
    },
    "yum": {
        "unicode": "1f60b",
        "unicode_alt": "",
        "code_decimal": "&#128523;",
        "name": "face savouring delicious food",
        "shortname": ":yum:",
        "channel": "people",
        "emoji_order": "11",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "silly", "smiley", "emotion", "sarcastic", "good"]
    },
    "sunglasses": {
        "unicode": "1f60e",
        "unicode_alt": "",
        "code_decimal": "&#128526;",
        "name": "smiling face with sunglasses",
        "shortname": ":sunglasses:",
        "channel": "people",
        "emoji_order": "12",
        "aliases": [],
        "aliases_ascii": ["B-)", "B)", "8)", "8-)", "B-D", "8-D"],
        "keywords": ["silly", "smiley", "emojione", "glasses", "boys night"]
    },
    "heart_eyes": {
        "unicode": "1f60d",
        "unicode_alt": "",
        "code_decimal": "&#128525;",
        "name": "smiling face with heart-shaped eyes",
        "shortname": ":heart_eyes:",
        "channel": "people",
        "emoji_order": "13",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "happy",
            "smiley",
            "love",
            "sex",
            "heart eyes",
            "emotion",
            "beautiful"
        ]
    },
    "kissing_heart": {
        "unicode": "1f618",
        "unicode_alt": "",
        "code_decimal": "&#128536;",
        "name": "face throwing a kiss",
        "shortname": ":kissing_heart:",
        "channel": "people",
        "emoji_order": "14",
        "aliases": [],
        "aliases_ascii": [":*", ":-*", "=*", ":^*"],
        "keywords": ["smiley", "love", "sexy"]
    },
    "kissing": {
        "unicode": "1f617",
        "unicode_alt": "",
        "code_decimal": "&#128535;",
        "name": "kissing face",
        "shortname": ":kissing:",
        "channel": "people",
        "emoji_order": "15",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "sexy"]
    },
    "kissing_smiling_eyes": {
        "unicode": "1f619",
        "unicode_alt": "",
        "code_decimal": "&#128537;",
        "name": "kissing face with smiling eyes",
        "shortname": ":kissing_smiling_eyes:",
        "channel": "people",
        "emoji_order": "16",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "sexy"]
    },
    "kissing_closed_eyes": {
        "unicode": "1f61a",
        "unicode_alt": "",
        "code_decimal": "&#128538;",
        "name": "kissing face with closed eyes",
        "shortname": ":kissing_closed_eyes:",
        "channel": "people",
        "emoji_order": "17",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "sexy"]
    },
    "relaxed": {
        "unicode": "263a",
        "unicode_alt": "263a-fe0f",
        "code_decimal": "&#9786;",
        "name": "white smiling face",
        "shortname": ":relaxed:",
        "channel": "people",
        "emoji_order": "18",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "smiley"]
    },
    "slight_smile": {
        "unicode": "1f642",
        "unicode_alt": "",
        "code_decimal": "&#128578;",
        "name": "slightly smiling face",
        "shortname": ":slight_smile:",
        "channel": "people",
        "emoji_order": "19",
        "aliases": [":slightly_smiling_face:"],
        "aliases_ascii": [":)", ":-)", "=]", "=)", ":]"],
        "keywords": ["happy", "smiley"]
    },
    "hugging": {
        "unicode": "1f917",
        "unicode_alt": "",
        "code_decimal": "&#129303;",
        "name": "hugging face",
        "shortname": ":hugging:",
        "channel": "people",
        "emoji_order": "20",
        "aliases": [":hugging_face:"],
        "aliases_ascii": [],
        "keywords": ["smiley", "hug", "thank you"]
    },
    "thinking": {
        "unicode": "1f914",
        "unicode_alt": "",
        "code_decimal": "&#129300;",
        "name": "thinking face",
        "shortname": ":thinking:",
        "channel": "people",
        "emoji_order": "21",
        "aliases": [":thinking_face:"],
        "aliases_ascii": [],
        "keywords": ["smiley", "thinking", "boys night"]
    },
    "neutral_face": {
        "unicode": "1f610",
        "unicode_alt": "",
        "code_decimal": "&#128528;",
        "name": "neutral face",
        "shortname": ":neutral_face:",
        "channel": "people",
        "emoji_order": "22",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["mad", "smiley", "shrug", "neutral", "emotion"]
    },
    "expressionless": {
        "unicode": "1f611",
        "unicode_alt": "",
        "code_decimal": "&#128529;",
        "name": "expressionless face",
        "shortname": ":expressionless:",
        "channel": "people",
        "emoji_order": "23",
        "aliases": [],
        "aliases_ascii": ["-_-", "-__-", "-___-"],
        "keywords": ["mad", "smiley", "neutral", "emotion"]
    },
    "no_mouth": {
        "unicode": "1f636",
        "unicode_alt": "",
        "code_decimal": "&#128566;",
        "name": "face without mouth",
        "shortname": ":no_mouth:",
        "channel": "people",
        "emoji_order": "24",
        "aliases": [],
        "aliases_ascii": [
            ":-X",
            ":X",
            ":-#",
            ":#",
            "=X",
            "=x",
            ":x",
            ":-x",
            "=#"
        ],
        "keywords": ["mad", "smiley", "neutral", "emotion"]
    },
    "rolling_eyes": {
        "unicode": "1f644",
        "unicode_alt": "",
        "code_decimal": "&#128580;",
        "name": "face with rolling eyes",
        "shortname": ":rolling_eyes:",
        "channel": "people",
        "emoji_order": "25",
        "aliases": [":face_with_rolling_eyes:"],
        "aliases_ascii": [],
        "keywords": ["mad", "smiley", "rolling eyes", "emotion", "sarcastic"]
    },
    "smirk": {
        "unicode": "1f60f",
        "unicode_alt": "",
        "code_decimal": "&#128527;",
        "name": "smirking face",
        "shortname": ":smirk:",
        "channel": "people",
        "emoji_order": "26",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["silly", "smiley", "sexy", "sarcastic"]
    },
    "persevere": {
        "unicode": "1f623",
        "unicode_alt": "",
        "code_decimal": "&#128547;",
        "name": "persevering face",
        "shortname": ":persevere:",
        "channel": "people",
        "emoji_order": "27",
        "aliases": [],
        "aliases_ascii": [">.<"],
        "keywords": ["sad", "smiley", "angry", "emotion"]
    },
    "disappointed_relieved": {
        "unicode": "1f625",
        "unicode_alt": "",
        "code_decimal": "&#128549;",
        "name": "disappointed but relieved face",
        "shortname": ":disappointed_relieved:",
        "channel": "people",
        "emoji_order": "28",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "stressed", "sweat", "cry", "emotion"]
    },
    "open_mouth": {
        "unicode": "1f62e",
        "unicode_alt": "",
        "code_decimal": "&#128558;",
        "name": "face with open mouth",
        "shortname": ":open_mouth:",
        "channel": "people",
        "emoji_order": "29",
        "aliases": [],
        "aliases_ascii": [":-O", ":O", ":-o", ":o", "O_O", ">:O"],
        "keywords": ["smiley", "surprised", "wow", "emotion"]
    },
    "zipper_mouth": {
        "unicode": "1f910",
        "unicode_alt": "",
        "code_decimal": "&#129296;",
        "name": "zipper-mouth face",
        "shortname": ":zipper_mouth:",
        "channel": "people",
        "emoji_order": "30",
        "aliases": [":zipper_mouth_face:"],
        "aliases_ascii": [],
        "keywords": ["mad", "smiley"]
    },
    "hushed": {
        "unicode": "1f62f",
        "unicode_alt": "",
        "code_decimal": "&#128559;",
        "name": "hushed face",
        "shortname": ":hushed:",
        "channel": "people",
        "emoji_order": "31",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "surprised", "wow"]
    },
    "sleepy": {
        "unicode": "1f62a",
        "unicode_alt": "",
        "code_decimal": "&#128554;",
        "name": "sleepy face",
        "shortname": ":sleepy:",
        "channel": "people",
        "emoji_order": "32",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "sick", "emotion"]
    },
    "tired_face": {
        "unicode": "1f62b",
        "unicode_alt": "",
        "code_decimal": "&#128555;",
        "name": "tired face",
        "shortname": ":tired_face:",
        "channel": "people",
        "emoji_order": "33",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "tired", "emotion"]
    },
    "sleeping": {
        "unicode": "1f634",
        "unicode_alt": "",
        "code_decimal": "&#128564;",
        "name": "sleeping face",
        "shortname": ":sleeping:",
        "channel": "people",
        "emoji_order": "34",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "tired", "emotion", "goodnight"]
    },
    "relieved": {
        "unicode": "1f60c",
        "unicode_alt": "",
        "code_decimal": "&#128524;",
        "name": "relieved face",
        "shortname": ":relieved:",
        "channel": "people",
        "emoji_order": "35",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "emotion"]
    },
    "nerd": {
        "unicode": "1f913",
        "unicode_alt": "",
        "code_decimal": "&#129299;",
        "name": "nerd face",
        "shortname": ":nerd:",
        "channel": "people",
        "emoji_order": "36",
        "aliases": [":nerd_face:"],
        "aliases_ascii": [],
        "keywords": ["smiley", "glasses"]
    },
    "stuck_out_tongue": {
        "unicode": "1f61b",
        "unicode_alt": "",
        "code_decimal": "&#128539;",
        "name": "face with stuck-out tongue",
        "shortname": ":stuck_out_tongue:",
        "channel": "people",
        "emoji_order": "37",
        "aliases": [],
        "aliases_ascii": [
            ":P",
            ":-P",
            "=P",
            ":-p",
            ":p",
            "=p",
            ":-Þ",
            ":Þ",
            ":þ",
            ":-þ",
            ":-b",
            ":b",
            "d:"
        ],
        "keywords": ["smiley", "sex", "emotion"]
    },
    "stuck_out_tongue_winking_eye": {
        "unicode": "1f61c",
        "unicode_alt": "",
        "code_decimal": "&#128540;",
        "name": "face with stuck-out tongue and winking eye",
        "shortname": ":stuck_out_tongue_winking_eye:",
        "channel": "people",
        "emoji_order": "38",
        "aliases": [],
        "aliases_ascii": [">:P", "X-P", "x-p"],
        "keywords": ["happy", "smiley", "emotion", "parties"]
    },
    "stuck_out_tongue_closed_eyes": {
        "unicode": "1f61d",
        "unicode_alt": "",
        "code_decimal": "&#128541;",
        "name": "face with stuck-out tongue and tightly-closed eyes",
        "shortname": ":stuck_out_tongue_closed_eyes:",
        "channel": "people",
        "emoji_order": "39",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "smiley", "emotion"]
    },
    "drooling_face": {
        "unicode": "1f924",
        "unicode_alt": "",
        "code_decimal": "&#129316;",
        "name": "drooling face",
        "shortname": ":drooling_face:",
        "channel": "people",
        "emoji_order": "40",
        "aliases": [":drool:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "unamused": {
        "unicode": "1f612",
        "unicode_alt": "",
        "code_decimal": "&#128530;",
        "name": "unamused face",
        "shortname": ":unamused:",
        "channel": "people",
        "emoji_order": "41",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "mad", "smiley", "tired", "emotion"]
    },
    "sweat": {
        "unicode": "1f613",
        "unicode_alt": "",
        "code_decimal": "&#128531;",
        "name": "face with cold sweat",
        "shortname": ":sweat:",
        "channel": "people",
        "emoji_order": "42",
        "aliases": [],
        "aliases_ascii": ["':(", "':-(", "'=("],
        "keywords": ["sad", "smiley", "stressed", "sweat", "emotion"]
    },
    "pensive": {
        "unicode": "1f614",
        "unicode_alt": "",
        "code_decimal": "&#128532;",
        "name": "pensive face",
        "shortname": ":pensive:",
        "channel": "people",
        "emoji_order": "43",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "emotion", "rip"]
    },
    "confused": {
        "unicode": "1f615",
        "unicode_alt": "",
        "code_decimal": "&#128533;",
        "name": "confused face",
        "shortname": ":confused:",
        "channel": "people",
        "emoji_order": "44",
        "aliases": [],
        "aliases_ascii": [
            ">:\\",
            ">:/",
            ":-/",
            ":-.",
            ":/",
            ":\\",
            "=/",
            "=\\",
            ":L",
            "=L"
        ],
        "keywords": ["smiley", "surprised", "emotion"]
    },
    "upside_down": {
        "unicode": "1f643",
        "unicode_alt": "",
        "code_decimal": "&#128579;",
        "name": "upside-down face",
        "shortname": ":upside_down:",
        "channel": "people",
        "emoji_order": "45",
        "aliases": [":upside_down_face:"],
        "aliases_ascii": [],
        "keywords": ["silly", "smiley", "sarcastic"]
    },
    "money_mouth": {
        "unicode": "1f911",
        "unicode_alt": "",
        "code_decimal": "&#129297;",
        "name": "money-mouth face",
        "shortname": ":money_mouth:",
        "channel": "people",
        "emoji_order": "46",
        "aliases": [":money_mouth_face:"],
        "aliases_ascii": [],
        "keywords": ["smiley", "win", "money", "emotion", "boys night"]
    },
    "astonished": {
        "unicode": "1f632",
        "unicode_alt": "",
        "code_decimal": "&#128562;",
        "name": "astonished face",
        "shortname": ":astonished:",
        "channel": "people",
        "emoji_order": "47",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "surprised", "wow", "emotion", "omg"]
    },
    "frowning2": {
        "unicode": "2639",
        "unicode_alt": "2639-fe0f",
        "code_decimal": "&#9785;",
        "name": "white frowning face",
        "shortname": ":frowning2:",
        "channel": "people",
        "emoji_order": "48",
        "aliases": [":white_frowning_face:"],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "emotion"]
    },
    "slight_frown": {
        "unicode": "1f641",
        "unicode_alt": "",
        "code_decimal": "&#128577;",
        "name": "slightly frowning face",
        "shortname": ":slight_frown:",
        "channel": "people",
        "emoji_order": "49",
        "aliases": [":slightly_frowning_face:"],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "emotion"]
    },
    "confounded": {
        "unicode": "1f616",
        "unicode_alt": "",
        "code_decimal": "&#128534;",
        "name": "confounded face",
        "shortname": ":confounded:",
        "channel": "people",
        "emoji_order": "50",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "angry", "emotion"]
    },
    "disappointed": {
        "unicode": "1f61e",
        "unicode_alt": "",
        "code_decimal": "&#128542;",
        "name": "disappointed face",
        "shortname": ":disappointed:",
        "channel": "people",
        "emoji_order": "51",
        "aliases": [],
        "aliases_ascii": [">:[", ":-(", ":(", ":-[", ":[", "=("],
        "keywords": ["sad", "smiley", "tired", "emotion"]
    },
    "worried": {
        "unicode": "1f61f",
        "unicode_alt": "",
        "code_decimal": "&#128543;",
        "name": "worried face",
        "shortname": ":worried:",
        "channel": "people",
        "emoji_order": "52",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "emotion"]
    },
    "triumph": {
        "unicode": "1f624",
        "unicode_alt": "",
        "code_decimal": "&#128548;",
        "name": "face with look of triumph",
        "shortname": ":triumph:",
        "channel": "people",
        "emoji_order": "53",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["mad", "smiley", "angry", "emotion", "steam"]
    },
    "cry": {
        "unicode": "1f622",
        "unicode_alt": "",
        "code_decimal": "&#128546;",
        "name": "crying face",
        "shortname": ":cry:",
        "channel": "people",
        "emoji_order": "54",
        "aliases": [],
        "aliases_ascii": [":'(", ":'-(", ";(", ";-("],
        "keywords": ["sad", "smiley", "cry", "emotion", "rip", "heartbreak"]
    },
    "sob": {
        "unicode": "1f62d",
        "unicode_alt": "",
        "code_decimal": "&#128557;",
        "name": "loudly crying face",
        "shortname": ":sob:",
        "channel": "people",
        "emoji_order": "55",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "cry", "emotion", "heartbreak"]
    },
    "frowning": {
        "unicode": "1f626",
        "unicode_alt": "",
        "code_decimal": "&#128550;",
        "name": "frowning face with open mouth",
        "shortname": ":frowning:",
        "channel": "people",
        "emoji_order": "56",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "surprised", "emotion"]
    },
    "anguished": {
        "unicode": "1f627",
        "unicode_alt": "",
        "code_decimal": "&#128551;",
        "name": "anguished face",
        "shortname": ":anguished:",
        "channel": "people",
        "emoji_order": "57",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "surprised", "emotion"]
    },
    "fearful": {
        "unicode": "1f628",
        "unicode_alt": "",
        "code_decimal": "&#128552;",
        "name": "fearful face",
        "shortname": ":fearful:",
        "channel": "people",
        "emoji_order": "58",
        "aliases": [],
        "aliases_ascii": ["D:"],
        "keywords": ["smiley", "surprised", "emotion"]
    },
    "weary": {
        "unicode": "1f629",
        "unicode_alt": "",
        "code_decimal": "&#128553;",
        "name": "weary face",
        "shortname": ":weary:",
        "channel": "people",
        "emoji_order": "59",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["sad", "smiley", "tired", "stressed", "emotion"]
    },
    "grimacing": {
        "unicode": "1f62c",
        "unicode_alt": "",
        "code_decimal": "&#128556;",
        "name": "grimacing face",
        "shortname": ":grimacing:",
        "channel": "people",
        "emoji_order": "60",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["silly", "smiley", "emotion", "selfie"]
    },
    "cold_sweat": {
        "unicode": "1f630",
        "unicode_alt": "",
        "code_decimal": "&#128560;",
        "name": "face with open mouth and cold sweat",
        "shortname": ":cold_sweat:",
        "channel": "people",
        "emoji_order": "61",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "sweat", "emotion"]
    },
    "scream": {
        "unicode": "1f631",
        "unicode_alt": "",
        "code_decimal": "&#128561;",
        "name": "face screaming in fear",
        "shortname": ":scream:",
        "channel": "people",
        "emoji_order": "62",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "surprised", "wow", "emotion", "omg"]
    },
    "flushed": {
        "unicode": "1f633",
        "unicode_alt": "",
        "code_decimal": "&#128563;",
        "name": "flushed face",
        "shortname": ":flushed:",
        "channel": "people",
        "emoji_order": "63",
        "aliases": [],
        "aliases_ascii": [":$", "=$"],
        "keywords": ["smiley", "emotion", "omg"]
    },
    "dizzy_face": {
        "unicode": "1f635",
        "unicode_alt": "",
        "code_decimal": "&#128565;",
        "name": "dizzy face",
        "shortname": ":dizzy_face:",
        "channel": "people",
        "emoji_order": "64",
        "aliases": [],
        "aliases_ascii": ["#-)", "#)", "%-)", "%)", "X)", "X-)"],
        "keywords": ["smiley", "surprised", "dead", "wow", "emotion", "omg"]
    },
    "rage": {
        "unicode": "1f621",
        "unicode_alt": "",
        "code_decimal": "&#128545;",
        "name": "pouting face",
        "shortname": ":rage:",
        "channel": "people",
        "emoji_order": "65",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["mad", "smiley", "angry", "emotion"]
    },
    "angry": {
        "unicode": "1f620",
        "unicode_alt": "",
        "code_decimal": "&#128544;",
        "name": "angry face",
        "shortname": ":angry:",
        "channel": "people",
        "emoji_order": "66",
        "aliases": [],
        "aliases_ascii": [">:(", ">:-(", ":@"],
        "keywords": ["mad", "smiley", "emotion"]
    },
    "innocent": {
        "unicode": "1f607",
        "unicode_alt": "",
        "code_decimal": "&#128519;",
        "name": "smiling face with halo",
        "shortname": ":innocent:",
        "channel": "people",
        "emoji_order": "67",
        "aliases": [],
        "aliases_ascii": [
            "O:-)",
            "0:-3",
            "0:3",
            "0:-)",
            "0:)",
            "0;^)",
            "O:)",
            "O;-)",
            "O=)",
            "0;-)",
            "O:-3",
            "O:3"
        ],
        "keywords": ["smiley", "emotion"]
    },
    "cowboy": {
        "unicode": "1f920",
        "unicode_alt": "",
        "code_decimal": "&#129312;",
        "name": "face with cowboy hat",
        "shortname": ":cowboy:",
        "channel": "people",
        "emoji_order": "68",
        "aliases": [":face_with_cowboy_hat:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "clown": {
        "unicode": "1f921",
        "unicode_alt": "",
        "code_decimal": "&#129313;",
        "name": "clown face",
        "shortname": ":clown:",
        "channel": "people",
        "emoji_order": "69",
        "aliases": [":clown_face:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "lying_face": {
        "unicode": "1f925",
        "unicode_alt": "",
        "code_decimal": "&#129317;",
        "name": "lying face",
        "shortname": ":lying_face:",
        "channel": "people",
        "emoji_order": "70",
        "aliases": [":liar:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "mask": {
        "unicode": "1f637",
        "unicode_alt": "",
        "code_decimal": "&#128567;",
        "name": "face with medical mask",
        "shortname": ":mask:",
        "channel": "people",
        "emoji_order": "71",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "dead", "health", "sick"]
    },
    "thermometer_face": {
        "unicode": "1f912",
        "unicode_alt": "",
        "code_decimal": "&#129298;",
        "name": "face with thermometer",
        "shortname": ":thermometer_face:",
        "channel": "people",
        "emoji_order": "72",
        "aliases": [":face_with_thermometer:"],
        "aliases_ascii": [],
        "keywords": ["smiley", "health", "sick", "emotion"]
    },
    "head_bandage": {
        "unicode": "1f915",
        "unicode_alt": "",
        "code_decimal": "&#129301;",
        "name": "face with head-bandage",
        "shortname": ":head_bandage:",
        "channel": "people",
        "emoji_order": "73",
        "aliases": [":face_with_head_bandage:"],
        "aliases_ascii": [],
        "keywords": ["smiley", "health", "sick", "emotion"]
    },
    "nauseated_face": {
        "unicode": "1f922",
        "unicode_alt": "",
        "code_decimal": "&#129314;",
        "name": "nauseated face",
        "shortname": ":nauseated_face:",
        "channel": "people",
        "emoji_order": "74",
        "aliases": [":sick:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "sneezing_face": {
        "unicode": "1f927",
        "unicode_alt": "",
        "code_decimal": "&#129319;",
        "name": "sneezing face",
        "shortname": ":sneezing_face:",
        "channel": "people",
        "emoji_order": "75",
        "aliases": [":sneeze:"],
        "aliases_ascii": [],
        "keywords": []
    },
    "smiling_imp": {
        "unicode": "1f608",
        "unicode_alt": "",
        "code_decimal": "&#128520;",
        "name": "smiling face with horns",
        "shortname": ":smiling_imp:",
        "channel": "people",
        "emoji_order": "76",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "silly",
            "smiley",
            "angry",
            "monster",
            "devil",
            "boys night"
        ]
    },
    "imp": {
        "unicode": "1f47f",
        "unicode_alt": "",
        "code_decimal": "&#128127;",
        "name": "imp",
        "shortname": ":imp:",
        "channel": "people",
        "emoji_order": "77",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["smiley", "monster", "devil", "wth"]
    },
    "japanese_ogre": {
        "unicode": "1f479",
        "unicode_alt": "",
        "code_decimal": "&#128121;",
        "name": "japanese ogre",
        "shortname": ":japanese_ogre:",
        "channel": "people",
        "emoji_order": "78",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["monster"]
    },
    "japanese_goblin": {
        "unicode": "1f47a",
        "unicode_alt": "",
        "code_decimal": "&#128122;",
        "name": "japanese goblin",
        "shortname": ":japanese_goblin:",
        "channel": "people",
        "emoji_order": "79",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["angry", "monster"]
    },
    "skull": {
        "unicode": "1f480",
        "unicode_alt": "",
        "code_decimal": "&#128128;",
        "name": "skull",
        "shortname": ":skull:",
        "channel": "people",
        "emoji_order": "80",
        "aliases": [":skeleton:"],
        "aliases_ascii": [],
        "keywords": ["dead", "halloween", "skull"]
    },
    "ghost": {
        "unicode": "1f47b",
        "unicode_alt": "",
        "code_decimal": "&#128123;",
        "name": "ghost",
        "shortname": ":ghost:",
        "channel": "people",
        "emoji_order": "82",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["holidays", "halloween", "monster"]
    },
    "alien": {
        "unicode": "1f47d",
        "unicode_alt": "",
        "code_decimal": "&#128125;",
        "name": "extraterrestrial alien",
        "shortname": ":alien:",
        "channel": "people",
        "emoji_order": "83",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["space", "monster", "alien", "scientology"]
    },
    "robot": {
        "unicode": "1f916",
        "unicode_alt": "",
        "code_decimal": "&#129302;",
        "name": "robot face",
        "shortname": ":robot:",
        "channel": "people",
        "emoji_order": "85",
        "aliases": [":robot_face:"],
        "aliases_ascii": [],
        "keywords": ["monster", "robot"]
    },
    "poop": {
        "unicode": "1f4a9",
        "unicode_alt": "",
        "code_decimal": "&#128169;",
        "name": "pile of poo",
        "shortname": ":poop:",
        "channel": "people",
        "emoji_order": "86",
        "aliases": [":shit:", ":hankey:", ":poo:"],
        "aliases_ascii": [],
        "keywords": ["bathroom", "shit", "sol", "diarrhea"]
    },
    "smiley_cat": {
        "unicode": "1f63a",
        "unicode_alt": "",
        "code_decimal": "&#128570;",
        "name": "smiling cat face with open mouth",
        "shortname": ":smiley_cat:",
        "channel": "people",
        "emoji_order": "87",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "cat", "animal"]
    },
    "smile_cat": {
        "unicode": "1f638",
        "unicode_alt": "",
        "code_decimal": "&#128568;",
        "name": "grinning cat face with smiling eyes",
        "shortname": ":smile_cat:",
        "channel": "people",
        "emoji_order": "88",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["happy", "cat", "animal"]
    },
    "joy_cat": {
        "unicode": "1f639",
        "unicode_alt": "",
        "code_decimal": "&#128569;",
        "name": "cat face with tears of joy",
        "shortname": ":joy_cat:",
        "channel": "people",
        "emoji_order": "89",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "happy",
            "silly",
            "cry",
            "laugh",
            "cat",
            "animal",
            "sarcastic"
        ]
    },
    "heart_eyes_cat": {
        "unicode": "1f63b",
        "unicode_alt": "",
        "code_decimal": "&#128571;",
        "name": "smiling cat face with heart-shaped eyes",
        "shortname": ":heart_eyes_cat:",
        "channel": "people",
        "emoji_order": "90",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["heart eyes", "cat", "animal", "beautiful"]
    },
    "smirk_cat": {
        "unicode": "1f63c",
        "unicode_alt": "",
        "code_decimal": "&#128572;",
        "name": "cat face with wry smile",
        "shortname": ":smirk_cat:",
        "channel": "people",
        "emoji_order": "91",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["cat", "animal"]
    },
    "kissing_cat": {
        "unicode": "1f63d",
        "unicode_alt": "",
        "code_decimal": "&#128573;",
        "name": "kissing cat face with closed eyes",
        "shortname": ":kissing_cat:",
        "channel": "people",
        "emoji_order": "92",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["cat", "animal"]
    },
    "scream_cat": {
        "unicode": "1f640",
        "unicode_alt": "",
        "code_decimal": "&#128576;",
        "name": "weary cat face",
        "shortname": ":scream_cat:",
        "channel": "people",
        "emoji_order": "93",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["cat", "animal"]
    },
    "crying_cat_face": {
        "unicode": "1f63f",
        "unicode_alt": "",
        "code_decimal": "&#128575;",
        "name": "crying cat face",
        "shortname": ":crying_cat_face:",
        "channel": "people",
        "emoji_order": "94",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["cry", "cat", "animal"]
    },
    "pouting_cat": {
        "unicode": "1f63e",
        "unicode_alt": "",
        "code_decimal": "&#128574;",
        "name": "pouting cat face",
        "shortname": ":pouting_cat:",
        "channel": "people",
        "emoji_order": "95",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["cat", "animal"]
    },
    "boy": {
        "unicode": "1f466",
        "unicode_alt": "",
        "code_decimal": "&#128102;",
        "name": "boy",
        "shortname": ":boy:",
        "channel": "people",
        "emoji_order": "99",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "baby", "diversity"]
    },
    "girl": {
        "unicode": "1f467",
        "unicode_alt": "",
        "code_decimal": "&#128103;",
        "name": "girl",
        "shortname": ":girl:",
        "channel": "people",
        "emoji_order": "105",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "baby", "diversity"]
    },
    "man": {
        "unicode": "1f468",
        "unicode_alt": "",
        "code_decimal": "&#128104;",
        "name": "man",
        "shortname": ":man:",
        "channel": "people",
        "emoji_order": "111",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "people",
            "men",
            "sex",
            "diversity",
            "selfie",
            "boys night"
        ]
    },

    "woman": {
        "unicode": "1f469",
        "unicode_alt": "",
        "code_decimal": "&#128105;",
        "name": "woman",
        "shortname": ":woman:",
        "channel": "people",
        "emoji_order": "117",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "people",
            "women",
            "sex",
            "diversity",
            "feminist",
            "selfie",
            "girls night"
        ]
    },

    "older_man": {
        "unicode": "1f474",
        "unicode_alt": "",
        "code_decimal": "&#128116;",
        "name": "older man",
        "shortname": ":older_man:",
        "channel": "people",
        "emoji_order": "123",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "men", "old people", "diversity"]
    },

    "older_woman": {
        "unicode": "1f475",
        "unicode_alt": "",
        "code_decimal": "&#128117;",
        "name": "older woman",
        "shortname": ":older_woman:",
        "channel": "people",
        "emoji_order": "129",
        "aliases": [":grandma:"],
        "aliases_ascii": [],
        "keywords": ["people", "old people", "diversity"]
    },

    "baby": {
        "unicode": "1f476",
        "unicode_alt": "",
        "code_decimal": "&#128118;",
        "name": "baby",
        "shortname": ":baby:",
        "channel": "people",
        "emoji_order": "135",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "baby", "diversity"]
    },

    "cop": {
        "unicode": "1f46e",
        "unicode_alt": "",
        "code_decimal": "&#128110;",
        "name": "police officer",
        "shortname": ":cop:",
        "channel": "people",
        "emoji_order": "339",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "people",
            "hat",
            "men",
            "diversity",
            "job",
            "police",
            "911"
        ]
    },

    "spy": {
        "unicode": "1f575",
        "unicode_alt": "1f575-fe0f",
        "code_decimal": "&#128373;",
        "name": "sleuth or spy",
        "shortname": ":spy:",
        "channel": "people",
        "emoji_order": "357",
        "aliases": [":sleuth_or_spy:"],
        "aliases_ascii": [],
        "keywords": ["people", "hat", "men", "glasses", "diversity", "job"]
    },

    "guardsman": {
        "unicode": "1f482",
        "unicode_alt": "",
        "code_decimal": "&#128130;",
        "name": "guardsman",
        "shortname": ":guardsman:",
        "channel": "people",
        "emoji_order": "375",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "hat", "men", "diversity", "job"]
    },

    "construction_worker": {
        "unicode": "1f477",
        "unicode_alt": "",
        "code_decimal": "&#128119;",
        "name": "construction worker",
        "shortname": ":construction_worker:",
        "channel": "people",
        "emoji_order": "393",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "hat", "men", "diversity", "job"]
    },

    "man_with_turban": {
        "unicode": "1f473",
        "unicode_alt": "",
        "code_decimal": "&#128115;",
        "name": "man with turban",
        "shortname": ":man_with_turban:",
        "channel": "people",
        "emoji_order": "411",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "hat", "diversity"]
    },

    "person_with_blond_hair": {
        "unicode": "1f471",
        "unicode_alt": "",
        "code_decimal": "&#128113;",
        "name": "person with blond hair",
        "shortname": ":person_with_blond_hair:",
        "channel": "people",
        "emoji_order": "429",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "men", "diversity"]
    },

    "santa": {
        "unicode": "1f385",
        "unicode_alt": "",
        "code_decimal": "&#127877;",
        "name": "father christmas",
        "shortname": ":santa:",
        "channel": "people",
        "emoji_order": "447",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "people",
            "hat",
            "winter",
            "holidays",
            "christmas",
            "diversity",
            "santa"
        ]
    },

    "mrs_claus": {
        "unicode": "1f936",
        "unicode_alt": "",
        "code_decimal": "&#129334;",
        "name": "mother christmas",
        "shortname": ":mrs_claus:",
        "channel": "people",
        "emoji_order": "453",
        "aliases": [":mother_christmas:"],
        "aliases_ascii": [],
        "keywords": []
    },

    "princess": {
        "unicode": "1f478",
        "unicode_alt": "",
        "code_decimal": "&#128120;",
        "name": "princess",
        "shortname": ":princess:",
        "channel": "people",
        "emoji_order": "459",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity", "beautiful", "girls night"]
    },

    "prince": {
        "unicode": "1f934",
        "unicode_alt": "",
        "code_decimal": "&#129332;",
        "name": "prince",
        "shortname": ":prince:",
        "channel": "people",
        "emoji_order": "465",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": []
    },

    "bride_with_veil": {
        "unicode": "1f470",
        "unicode_alt": "",
        "code_decimal": "&#128112;",
        "name": "bride with veil",
        "shortname": ":bride_with_veil:",
        "channel": "people",
        "emoji_order": "471",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "wedding", "women", "diversity"]
    },

    "man_in_tuxedo": {
        "unicode": "1f935",
        "unicode_alt": "",
        "code_decimal": "&#129333;",
        "name": "man in tuxedo",
        "shortname": ":man_in_tuxedo:",
        "channel": "people",
        "emoji_order": "477",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": []
    },

    "pregnant_woman": {
        "unicode": "1f930",
        "unicode_alt": "",
        "code_decimal": "&#129328;",
        "name": "pregnant woman",
        "shortname": ":pregnant_woman:",
        "channel": "people",
        "emoji_order": "483",
        "aliases": [":expecting_woman:"],
        "aliases_ascii": [],
        "keywords": []
    },

    "man_with_gua_pi_mao": {
        "unicode": "1f472",
        "unicode_alt": "",
        "code_decimal": "&#128114;",
        "name": "man with gua pi mao",
        "shortname": ":man_with_gua_pi_mao:",
        "channel": "people",
        "emoji_order": "489",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "hat", "men", "diversity"]
    },

    "person_frowning": {
        "unicode": "1f64d",
        "unicode_alt": "",
        "code_decimal": "&#128589;",
        "name": "person frowning",
        "shortname": ":person_frowning:",
        "channel": "people",
        "emoji_order": "495",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity"]
    },

    "person_with_pouting_face": {
        "unicode": "1f64e",
        "unicode_alt": "",
        "code_decimal": "&#128590;",
        "name": "person with pouting face",
        "shortname": ":person_with_pouting_face:",
        "channel": "people",
        "emoji_order": "513",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity"]
    },

    "no_good": {
        "unicode": "1f645",
        "unicode_alt": "",
        "code_decimal": "&#128581;",
        "name": "face with no good gesture",
        "shortname": ":no_good:",
        "channel": "people",
        "emoji_order": "531",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity", "girls night"]
    },

    "ok_woman": {
        "unicode": "1f646",
        "unicode_alt": "",
        "code_decimal": "&#128582;",
        "name": "face with ok gesture",
        "shortname": ":ok_woman:",
        "channel": "people",
        "emoji_order": "549",
        "aliases": [],
        "aliases_ascii": ["*\\0/*", "\\0/", "*\\O/*", "\\O/"],
        "keywords": ["people", "women", "diversity"]
    },

    "information_desk_person": {
        "unicode": "1f481",
        "unicode_alt": "",
        "code_decimal": "&#128129;",
        "name": "information desk person",
        "shortname": ":information_desk_person:",
        "channel": "people",
        "emoji_order": "567",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity"]
    },

    "raising_hand": {
        "unicode": "1f64b",
        "unicode_alt": "",
        "code_decimal": "&#128587;",
        "name": "happy person raising one hand",
        "shortname": ":raising_hand:",
        "channel": "people",
        "emoji_order": "585",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity"]
    },

    "bow": {
        "unicode": "1f647",
        "unicode_alt": "",
        "code_decimal": "&#128583;",
        "name": "person bowing deeply",
        "shortname": ":bow:",
        "channel": "people",
        "emoji_order": "603",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "pray", "diversity"]
    },

    "face_palm": {
        "unicode": "1f926",
        "unicode_alt": "",
        "code_decimal": "&#129318;",
        "name": "face palm",
        "shortname": ":face_palm:",
        "channel": "people",
        "emoji_order": "621",
        "aliases": [":facepalm:"],
        "aliases_ascii": [],
        "keywords": []
    },

    "shrug": {
        "unicode": "1f937",
        "unicode_alt": "",
        "code_decimal": "&#129335;",
        "name": "shrug",
        "shortname": ":shrug:",
        "channel": "people",
        "emoji_order": "639",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": []
    },

    "massage": {
        "unicode": "1f486",
        "unicode_alt": "",
        "code_decimal": "&#128134;",
        "name": "face massage",
        "shortname": ":massage:",
        "channel": "people",
        "emoji_order": "657",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity"]
    },

    "haircut": {
        "unicode": "1f487",
        "unicode_alt": "",
        "code_decimal": "&#128135;",
        "name": "haircut",
        "shortname": ":haircut:",
        "channel": "people",
        "emoji_order": "675",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "diversity"]
    },

    "walking": {
        "unicode": "1f6b6",
        "unicode_alt": "",
        "code_decimal": "&#128694;",
        "name": "pedestrian",
        "shortname": ":walking:",
        "channel": "people",
        "emoji_order": "693",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "men", "diversity"]
    },

    "runner": {
        "unicode": "1f3c3",
        "unicode_alt": "",
        "code_decimal": "&#127939;",
        "name": "runner",
        "shortname": ":runner:",
        "channel": "people",
        "emoji_order": "711",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "men", "diversity", "boys night", "run"]
    },

    "dancer": {
        "unicode": "1f483",
        "unicode_alt": "",
        "code_decimal": "&#128131;",
        "name": "dancer",
        "shortname": ":dancer:",
        "channel": "people",
        "emoji_order": "729",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "people",
            "women",
            "sexy",
            "diversity",
            "girls night",
            "dance"
        ]
    },

    "man_dancing": {
        "unicode": "1f57a",
        "unicode_alt": "",
        "code_decimal": "&#128378;",
        "name": "man dancing",
        "shortname": ":man_dancing:",
        "channel": "people",
        "emoji_order": "735",
        "aliases": [":male_dancer:"],
        "aliases_ascii": [],
        "keywords": []
    },

    "dancers": {
        "unicode": "1f46f",
        "unicode_alt": "",
        "code_decimal": "&#128111;",
        "name": "woman with bunny ears",
        "shortname": ":dancers:",
        "channel": "people",
        "emoji_order": "741",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "people",
            "women",
            "sexy",
            "girls night",
            "boys night",
            "parties",
            "dance"
        ]
    },
    "speaking_head": {
        "unicode": "1f5e3",
        "unicode_alt": "1f5e3-fe0f",
        "code_decimal": "&#128483;",
        "name": "speaking head in silhouette",
        "shortname": ":speaking_head:",
        "channel": "people",
        "emoji_order": "765",
        "aliases": [":speaking_head_in_silhouette:"],
        "aliases_ascii": [],
        "keywords": ["people", "talk"]
    },
    "bust_in_silhouette": {
        "unicode": "1f464",
        "unicode_alt": "",
        "code_decimal": "&#128100;",
        "name": "bust in silhouette",
        "shortname": ":bust_in_silhouette:",
        "channel": "people",
        "emoji_order": "766",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people"]
    },
    "busts_in_silhouette": {
        "unicode": "1f465",
        "unicode_alt": "",
        "code_decimal": "&#128101;",
        "name": "busts in silhouette",
        "shortname": ":busts_in_silhouette:",
        "channel": "people",
        "emoji_order": "767",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people"]
    },
    "couple": {
        "unicode": "1f46b",
        "unicode_alt": "",
        "code_decimal": "&#128107;",
        "name": "man and woman holding hands",
        "shortname": ":couple:",
        "channel": "people",
        "emoji_order": "1018",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "sex", "creationism"]
    },
    "two_men_holding_hands": {
        "unicode": "1f46c",
        "unicode_alt": "",
        "code_decimal": "&#128108;",
        "name": "two men holding hands",
        "shortname": ":two_men_holding_hands:",
        "channel": "people",
        "emoji_order": "1024",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "men", "sex", "lgbt"]
    },
    "two_women_holding_hands": {
        "unicode": "1f46d",
        "unicode_alt": "",
        "code_decimal": "&#128109;",
        "name": "two women holding hands",
        "shortname": ":two_women_holding_hands:",
        "channel": "people",
        "emoji_order": "1030",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "women", "sex", "lgbt", "lesbian", "girls night"]
    },
    "couplekiss": {
        "unicode": "1f48f",
        "unicode_alt": "",
        "code_decimal": "&#128143;",
        "name": "kiss",
        "shortname": ":couplekiss:",
        "channel": "people",
        "emoji_order": "1036",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "love", "sex"]
    },
    "kiss_mm": {
        "unicode": "1f468-2764-1f48b-1f468",
        "unicode_alt": "1f468-200d-2764-fe0f-200d-1f48b-200d-1f468",
        "code_decimal": "&#128104;&#10084;&#128139;&#128104;",
        "name": "kiss (man,man)",
        "shortname": ":kiss_mm:",
        "channel": "people",
        "emoji_order": "1038",
        "aliases": [":couplekiss_mm:"],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "men", "love", "sex", "lgbt"]
    },
    "kiss_ww": {
        "unicode": "1f469-2764-1f48b-1f469",
        "unicode_alt": "1f469-200d-2764-fe0f-200d-1f48b-200d-1f469",
        "code_decimal": "&#128105;&#10084;&#128139;&#128105;",
        "name": "kiss (woman,woman)",
        "shortname": ":kiss_ww:",
        "channel": "people",
        "emoji_order": "1039",
        "aliases": [":couplekiss_ww:"],
        "aliases_ascii": [],
        "keywords": ["people", "women", "love", "sex", "lgbt", "lesbian"]
    },
    "couple_with_heart": {
        "unicode": "1f491",
        "unicode_alt": "",
        "code_decimal": "&#128145;",
        "name": "couple with heart",
        "shortname": ":couple_with_heart:",
        "channel": "people",
        "emoji_order": "1040",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "love", "sex"]
    },
    "couple_mm": {
        "unicode": "1f468-2764-1f468",
        "unicode_alt": "1f468-200d-2764-fe0f-200d-1f468",
        "code_decimal": "&#128104;&#10084;&#128104;",
        "name": "couple (man,man)",
        "shortname": ":couple_mm:",
        "channel": "people",
        "emoji_order": "1042",
        "aliases": [":couple_with_heart_mm:"],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "men", "love", "sex", "lgbt"]
    },
    "couple_ww": {
        "unicode": "1f469-2764-1f469",
        "unicode_alt": "1f469-200d-2764-fe0f-200d-1f469",
        "code_decimal": "&#128105;&#10084;&#128105;",
        "name": "couple (woman,woman)",
        "shortname": ":couple_ww:",
        "channel": "people",
        "emoji_order": "1043",
        "aliases": [":couple_with_heart_ww:"],
        "aliases_ascii": [],
        "keywords": ["people", "women", "love", "sex", "lgbt"]
    },
    "family": {
        "unicode": "1f46a",
        "unicode_alt": "",
        "code_decimal": "&#128106;",
        "name": "family",
        "shortname": ":family:",
        "channel": "people",
        "emoji_order": "1044",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "baby"]
    },
    "family_mwg": {
        "unicode": "1f468-1f469-1f467",
        "unicode_alt": "1f468-200d-1f469-200d-1f467",
        "code_decimal": "&#128104;&#128105;&#128103;",
        "name": "family (man,woman,girl)",
        "shortname": ":family_mwg:",
        "channel": "people",
        "emoji_order": "1051",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "baby"]
    },
    "family_mwgb": {
        "unicode": "1f468-1f469-1f467-1f466",
        "unicode_alt": "1f468-200d-1f469-200d-1f467-200d-1f466",
        "code_decimal": "&#128104;&#128105;&#128103;&#128102;",
        "name": "family (man,woman,girl,boy)",
        "shortname": ":family_mwgb:",
        "channel": "people",
        "emoji_order": "1052",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "baby"]
    },
    "family_mwbb": {
        "unicode": "1f468-1f469-1f466-1f466",
        "unicode_alt": "1f468-200d-1f469-200d-1f466-200d-1f466",
        "code_decimal": "&#128104;&#128105;&#128102;&#128102;",
        "name": "family (man,woman,boy,boy)",
        "shortname": ":family_mwbb:",
        "channel": "people",
        "emoji_order": "1053",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "baby"]
    },
    "family_mwgg": {
        "unicode": "1f468-1f469-1f467-1f467",
        "unicode_alt": "1f468-200d-1f469-200d-1f467-200d-1f467",
        "code_decimal": "&#128104;&#128105;&#128103;&#128103;",
        "name": "family (man,woman,girl,girl)",
        "shortname": ":family_mwgg:",
        "channel": "people",
        "emoji_order": "1054",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "baby"]
    },
    "family_mmb": {
        "unicode": "1f468-1f468-1f466",
        "unicode_alt": "1f468-200d-1f468-200d-1f466",
        "code_decimal": "&#128104;&#128104;&#128102;",
        "name": "family (man,man,boy)",
        "shortname": ":family_mmb:",
        "channel": "people",
        "emoji_order": "1055",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "family", "men", "baby", "lgbt"]
    },
    "family_mmg": {
        "unicode": "1f468-1f468-1f467",
        "unicode_alt": "1f468-200d-1f468-200d-1f467",
        "code_decimal": "&#128104;&#128104;&#128103;",
        "name": "family (man,man,girl)",
        "shortname": ":family_mmg:",
        "channel": "people",
        "emoji_order": "1056",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "family", "men", "baby", "lgbt"]
    },
    "family_mmgb": {
        "unicode": "1f468-1f468-1f467-1f466",
        "unicode_alt": "1f468-200d-1f468-200d-1f467-200d-1f466",
        "code_decimal": "&#128104;&#128104;&#128103;&#128102;",
        "name": "family (man,man,girl,boy)",
        "shortname": ":family_mmgb:",
        "channel": "people",
        "emoji_order": "1057",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "family", "men", "baby", "lgbt"]
    },
    "family_mmbb": {
        "unicode": "1f468-1f468-1f466-1f466",
        "unicode_alt": "1f468-200d-1f468-200d-1f466-200d-1f466",
        "code_decimal": "&#128104;&#128104;&#128102;&#128102;",
        "name": "family (man,man,boy,boy)",
        "shortname": ":family_mmbb:",
        "channel": "people",
        "emoji_order": "1058",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "family", "men", "baby", "lgbt"]
    },
    "family_mmgg": {
        "unicode": "1f468-1f468-1f467-1f467",
        "unicode_alt": "1f468-200d-1f468-200d-1f467-200d-1f467",
        "code_decimal": "&#128104;&#128104;&#128103;&#128103;",
        "name": "family (man,man,girl,girl)",
        "shortname": ":family_mmgg:",
        "channel": "people",
        "emoji_order": "1059",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "gay", "family", "men", "baby", "lgbt"]
    },
    "family_wwb": {
        "unicode": "1f469-1f469-1f466",
        "unicode_alt": "1f469-200d-1f469-200d-1f466",
        "code_decimal": "&#128105;&#128105;&#128102;",
        "name": "family (woman,woman,boy)",
        "shortname": ":family_wwb:",
        "channel": "people",
        "emoji_order": "1060",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "women", "baby", "lgbt", "lesbian"]
    },
    "family_wwg": {
        "unicode": "1f469-1f469-1f467",
        "unicode_alt": "1f469-200d-1f469-200d-1f467",
        "code_decimal": "&#128105;&#128105;&#128103;",
        "name": "family (woman,woman,girl)",
        "shortname": ":family_wwg:",
        "channel": "people",
        "emoji_order": "1061",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "women", "baby", "lgbt", "lesbian"]
    },
    "family_wwgb": {
        "unicode": "1f469-1f469-1f467-1f466",
        "unicode_alt": "1f469-200d-1f469-200d-1f467-200d-1f466",
        "code_decimal": "&#128105;&#128105;&#128103;&#128102;",
        "name": "family (woman,woman,girl,boy)",
        "shortname": ":family_wwgb:",
        "channel": "people",
        "emoji_order": "1062",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "women", "baby", "lgbt", "lesbian"]
    },
    "family_wwbb": {
        "unicode": "1f469-1f469-1f466-1f466",
        "unicode_alt": "1f469-200d-1f469-200d-1f466-200d-1f466",
        "code_decimal": "&#128105;&#128105;&#128102;&#128102;",
        "name": "family (woman,woman,boy,boy)",
        "shortname": ":family_wwbb:",
        "channel": "people",
        "emoji_order": "1063",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "women", "baby", "lgbt", "lesbian"]
    },
    "family_wwgg": {
        "unicode": "1f469-1f469-1f467-1f467",
        "unicode_alt": "1f469-200d-1f469-200d-1f467-200d-1f467",
        "code_decimal": "&#128105;&#128105;&#128103;&#128103;",
        "name": "family (woman,woman,girl,girl)",
        "shortname": ":family_wwgg:",
        "channel": "people",
        "emoji_order": "1064",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["people", "family", "women", "baby", "lgbt", "lesbian"]
    },
    "muscle": {
        "unicode": "1f4aa",
        "unicode_alt": "",
        "code_decimal": "&#128170;",
        "name": "flexed biceps",
        "shortname": ":muscle:",
        "channel": "people",
        "emoji_order": "1080",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "workout",
            "flex",
            "win",
            "diversity",
            "feminist",
            "boys night"
        ]
    },

    "selfie": {
        "unicode": "1f933",
        "unicode_alt": "",
        "code_decimal": "&#129331;",
        "name": "selfie",
        "shortname": ":selfie:",
        "channel": "people",
        "emoji_order": "1086",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": []
    },

    "point_left": {
        "unicode": "1f448",
        "unicode_alt": "",
        "code_decimal": "&#128072;",
        "name": "white left pointing backhand index",
        "shortname": ":point_left:",
        "channel": "people",
        "emoji_order": "1092",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "hi", "diversity"]
    },

    "point_right": {
        "unicode": "1f449",
        "unicode_alt": "",
        "code_decimal": "&#128073;",
        "name": "white right pointing backhand index",
        "shortname": ":point_right:",
        "channel": "people",
        "emoji_order": "1098",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "hi", "diversity"]
    },

    "point_up": {
        "unicode": "261d",
        "unicode_alt": "261d-fe0f",
        "code_decimal": "&#9757;",
        "name": "white up pointing index",
        "shortname": ":point_up:",
        "channel": "people",
        "emoji_order": "1104",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "emojione", "diversity"]
    },

    "point_up_2": {
        "unicode": "1f446",
        "unicode_alt": "",
        "code_decimal": "&#128070;",
        "name": "white up pointing backhand index",
        "shortname": ":point_up_2:",
        "channel": "people",
        "emoji_order": "1110",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "diversity"]
    },

    "middle_finger": {
        "unicode": "1f595",
        "unicode_alt": "",
        "code_decimal": "&#128405;",
        "name": "reversed hand with middle finger extended",
        "shortname": ":middle_finger:",
        "channel": "people",
        "emoji_order": "1116",
        "aliases": [":reversed_hand_with_middle_finger_extended:"],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "middle finger", "diversity"]
    },

    "point_down": {
        "unicode": "1f447",
        "unicode_alt": "",
        "code_decimal": "&#128071;",
        "name": "white down pointing backhand index",
        "shortname": ":point_down:",
        "channel": "people",
        "emoji_order": "1122",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "diversity"]
    },

    "v": {
        "unicode": "270c",
        "unicode_alt": "270c-fe0f",
        "code_decimal": "&#9996;",
        "name": "victory hand",
        "shortname": ":v:",
        "channel": "people",
        "emoji_order": "1128",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "thank you",
            "peace",
            "diversity",
            "girls night"
        ]
    },
  
    "fingers_crossed": {
        "unicode": "1f91e",
        "unicode_alt": "",
        "code_decimal": "&#129310;",
        "name": "hand with first and index finger crossed",
        "shortname": ":fingers_crossed:",
        "channel": "people",
        "emoji_order": "1134",
        "aliases": [":hand_with_index_and_middle_finger_crossed:"],
        "aliases_ascii": [],
        "keywords": []
    },
   
    "vulcan": {
        "unicode": "1f596",
        "unicode_alt": "",
        "code_decimal": "&#128406;",
        "name": "raised hand with part between middle and ring fingers",
        "shortname": ":vulcan:",
        "channel": "people",
        "emoji_order": "1140",
        "aliases": [":raised_hand_with_part_between_middle_and_ring_fingers:"],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "hi", "diversity"]
    },
  
    "metal": {
        "unicode": "1f918",
        "unicode_alt": "",
        "code_decimal": "&#129304;",
        "name": "sign of the horns",
        "shortname": ":metal:",
        "channel": "people",
        "emoji_order": "1146",
        "aliases": [":sign_of_the_horns:"],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "diversity",
            "boys night",
            "parties"
        ]
    },
    
    "call_me": {
        "unicode": "1f919",
        "unicode_alt": "",
        "code_decimal": "&#129305;",
        "name": "call me hand",
        "shortname": ":call_me:",
        "channel": "people",
        "emoji_order": "1152",
        "aliases": [":call_me_hand:"],
        "aliases_ascii": [],
        "keywords": []
    },
    
    "hand_splayed": {
        "unicode": "1f590",
        "unicode_alt": "1f590-fe0f",
        "code_decimal": "&#128400;",
        "name": "raised hand with fingers splayed",
        "shortname": ":hand_splayed:",
        "channel": "people",
        "emoji_order": "1158",
        "aliases": [":raised_hand_with_fingers_splayed:"],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "hi", "diversity"]
    },
    
    "raised_hand": {
        "unicode": "270b",
        "unicode_alt": "",
        "code_decimal": "&#9995;",
        "name": "raised hand",
        "shortname": ":raised_hand:",
        "channel": "people",
        "emoji_order": "1164",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "hi", "diversity", "girls night"]
    },
   
    "ok_hand": {
        "unicode": "1f44c",
        "unicode_alt": "",
        "code_decimal": "&#128076;",
        "name": "ok hand sign",
        "shortname": ":ok_hand:",
        "channel": "people",
        "emoji_order": "1170",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "diversity",
            "perfect",
            "good",
            "beautiful"
        ]
    },
   
    "thumbsup": {
        "unicode": "1f44d",
        "unicode_alt": "",
        "code_decimal": "&#128077;",
        "name": "thumbs up sign",
        "shortname": ":thumbsup:",
        "channel": "people",
        "emoji_order": "1176",
        "aliases": [":+1:", ":thumbup:"],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "luck",
            "thank you",
            "diversity",
            "perfect",
            "good",
            "beautiful"
        ]
    },
   
    "thumbsdown": {
        "unicode": "1f44e",
        "unicode_alt": "",
        "code_decimal": "&#128078;",
        "name": "thumbs down sign",
        "shortname": ":thumbsdown:",
        "channel": "people",
        "emoji_order": "1182",
        "aliases": [":-1:", ":thumbdown:"],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "diversity"]
    },
  
    "fist": {
        "unicode": "270a",
        "unicode_alt": "",
        "code_decimal": "&#9994;",
        "name": "raised fist",
        "shortname": ":fist:",
        "channel": "people",
        "emoji_order": "1188",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "fist bump",
            "diversity",
            "condolence"
        ]
    },
   
    "punch": {
        "unicode": "1f44a",
        "unicode_alt": "",
        "code_decimal": "&#128074;",
        "name": "fisted hand sign",
        "shortname": ":punch:",
        "channel": "people",
        "emoji_order": "1194",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "fist bump",
            "diversity",
            "boys night"
        ]
    },
  
    "left_facing_fist": {
        "unicode": "1f91b",
        "unicode_alt": "",
        "code_decimal": "&#129307;",
        "name": "left-facing fist",
        "shortname": ":left_facing_fist:",
        "channel": "people",
        "emoji_order": "1200",
        "aliases": [":left_fist:"],
        "aliases_ascii": [],
        "keywords": []
    },
   
    "right_facing_fist": {
        "unicode": "1f91c",
        "unicode_alt": "",
        "code_decimal": "&#129308;",
        "name": "right-facing fist",
        "shortname": ":right_facing_fist:",
        "channel": "people",
        "emoji_order": "1206",
        "aliases": [":right_fist:"],
        "aliases_ascii": [],
        "keywords": []
    },
    
    "raised_back_of_hand": {
        "unicode": "1f91a",
        "unicode_alt": "",
        "code_decimal": "&#129306;",
        "name": "raised back of hand",
        "shortname": ":raised_back_of_hand:",
        "channel": "people",
        "emoji_order": "1212",
        "aliases": [":back_of_hand:"],
        "aliases_ascii": [],
        "keywords": []
    },
    
    "wave": {
        "unicode": "1f44b",
        "unicode_alt": "",
        "code_decimal": "&#128075;",
        "name": "waving hand sign",
        "shortname": ":wave:",
        "channel": "people",
        "emoji_order": "1218",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "hi", "diversity"]
    },
   
    "clap": {
        "unicode": "1f44f",
        "unicode_alt": "",
        "code_decimal": "&#128079;",
        "name": "clapping hands sign",
        "shortname": ":clap:",
        "channel": "people",
        "emoji_order": "1224",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "win", "diversity", "good", "beautiful"]
    },
    
    "writing_hand": {
        "unicode": "270d",
        "unicode_alt": "270d-fe0f",
        "code_decimal": "&#9997;",
        "name": "writing hand",
        "shortname": ":writing_hand:",
        "channel": "people",
        "emoji_order": "1230",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "write", "diversity"]
    },
   
    "open_hands": {
        "unicode": "1f450",
        "unicode_alt": "",
        "code_decimal": "&#128080;",
        "name": "open hands sign",
        "shortname": ":open_hands:",
        "channel": "people",
        "emoji_order": "1236",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "diversity", "condolence"]
    },
   
    "raised_hands": {
        "unicode": "1f64c",
        "unicode_alt": "",
        "code_decimal": "&#128588;",
        "name": "person raising both hands in celebration",
        "shortname": ":raised_hands:",
        "channel": "people",
        "emoji_order": "1242",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "hands", "diversity", "perfect", "good", "parties"]
    },
   
    "pray": {
        "unicode": "1f64f",
        "unicode_alt": "",
        "code_decimal": "&#128591;",
        "name": "person with folded hands",
        "shortname": ":pray:",
        "channel": "people",
        "emoji_order": "1248",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "body",
            "hands",
            "hi",
            "luck",
            "thank you",
            "pray",
            "diversity",
            "scientology"
        ]
    },
   
    "handshake": {
        "unicode": "1f91d",
        "unicode_alt": "",
        "code_decimal": "&#129309;",
        "name": "handshake",
        "shortname": ":handshake:",
        "channel": "people",
        "emoji_order": "1254",
        "aliases": [":shaking_hands:"],
        "aliases_ascii": [],
        "keywords": []
    },
   
    "nail_care": {
        "unicode": "1f485",
        "unicode_alt": "",
        "code_decimal": "&#128133;",
        "name": "nail polish",
        "shortname": ":nail_care:",
        "channel": "people",
        "emoji_order": "1260",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "women",
            "body",
            "hands",
            "nailpolish",
            "diversity",
            "girls night"
        ]
    },
  
    "ear": {
        "unicode": "1f442",
        "unicode_alt": "",
        "code_decimal": "&#128066;",
        "name": "ear",
        "shortname": ":ear:",
        "channel": "people",
        "emoji_order": "1266",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "diversity"]
    },
   
    "nose": {
        "unicode": "1f443",
        "unicode_alt": "",
        "code_decimal": "&#128067;",
        "name": "nose",
        "shortname": ":nose:",
        "channel": "people",
        "emoji_order": "1272",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "diversity"]
    },
   
    "footprints": {
        "unicode": "1f463",
        "unicode_alt": "",
        "code_decimal": "&#128099;",
        "name": "footprints",
        "shortname": ":footprints:",
        "channel": "people",
        "emoji_order": "1278",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": []
    },
    "eyes": {
        "unicode": "1f440",
        "unicode_alt": "",
        "code_decimal": "&#128064;",
        "name": "eyes",
        "shortname": ":eyes:",
        "channel": "people",
        "emoji_order": "1279",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "eyes"]
    },
    "eye": {
        "unicode": "1f441",
        "unicode_alt": "1f441-fe0f",
        "code_decimal": "&#128065;",
        "name": "eye",
        "shortname": ":eye:",
        "channel": "people",
        "emoji_order": "1280",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "eyes"]
    },
    "tongue": {
        "unicode": "1f445",
        "unicode_alt": "",
        "code_decimal": "&#128069;",
        "name": "tongue",
        "shortname": ":tongue:",
        "channel": "people",
        "emoji_order": "1282",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["body", "sexy", "lip"]
    },
    "lips": {
        "unicode": "1f444",
        "unicode_alt": "",
        "code_decimal": "&#128068;",
        "name": "mouth",
        "shortname": ":lips:",
        "channel": "people",
        "emoji_order": "1283",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "body", "sexy", "lip"]
    },
    "kiss": {
        "unicode": "1f48b",
        "unicode_alt": "",
        "code_decimal": "&#128139;",
        "name": "kiss mark",
        "shortname": ":kiss:",
        "channel": "people",
        "emoji_order": "1284",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "love", "sexy", "lip", "beautiful", "girls night"]
    },
    "zzz": {
        "unicode": "1f4a4",
        "unicode_alt": "",
        "code_decimal": "&#128164;",
        "name": "sleeping symbol",
        "shortname": ":zzz:",
        "channel": "people",
        "emoji_order": "1302",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["tired", "goodnight"]
    },
    "eyeglasses": {
        "unicode": "1f453",
        "unicode_alt": "",
        "code_decimal": "&#128083;",
        "name": "eyeglasses",
        "shortname": ":eyeglasses:",
        "channel": "people",
        "emoji_order": "1314",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion", "glasses", "accessories"]
    },
    "dark_sunglasses": {
        "unicode": "1f576",
        "unicode_alt": "1f576-fe0f",
        "code_decimal": "&#128374;",
        "name": "dark sunglasses",
        "shortname": ":dark_sunglasses:",
        "channel": "people",
        "emoji_order": "1315",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion", "glasses", "accessories"]
    },
    "necktie": {
        "unicode": "1f454",
        "unicode_alt": "",
        "code_decimal": "&#128084;",
        "name": "necktie",
        "shortname": ":necktie:",
        "channel": "people",
        "emoji_order": "1316",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion"]
    },
    "shirt": {
        "unicode": "1f455",
        "unicode_alt": "",
        "code_decimal": "&#128085;",
        "name": "t-shirt",
        "shortname": ":shirt:",
        "channel": "people",
        "emoji_order": "1317",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion"]
    },
    "jeans": {
        "unicode": "1f456",
        "unicode_alt": "",
        "code_decimal": "&#128086;",
        "name": "jeans",
        "shortname": ":jeans:",
        "channel": "people",
        "emoji_order": "1318",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion"]
    },
    "dress": {
        "unicode": "1f457",
        "unicode_alt": "",
        "code_decimal": "&#128087;",
        "name": "dress",
        "shortname": ":dress:",
        "channel": "people",
        "emoji_order": "1319",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "fashion", "sexy", "girls night"]
    },
    "kimono": {
        "unicode": "1f458",
        "unicode_alt": "",
        "code_decimal": "&#128088;",
        "name": "kimono",
        "shortname": ":kimono:",
        "channel": "people",
        "emoji_order": "1320",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion"]
    },
    "bikini": {
        "unicode": "1f459",
        "unicode_alt": "",
        "code_decimal": "&#128089;",
        "name": "bikini",
        "shortname": ":bikini:",
        "channel": "people",
        "emoji_order": "1321",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "fashion", "sexy", "vacation", "tropical", "swim"]
    },
    "womans_clothes": {
        "unicode": "1f45a",
        "unicode_alt": "",
        "code_decimal": "&#128090;",
        "name": "womans clothes",
        "shortname": ":womans_clothes:",
        "channel": "people",
        "emoji_order": "1322",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "fashion"]
    },
    "purse": {
        "unicode": "1f45b",
        "unicode_alt": "",
        "code_decimal": "&#128091;",
        "name": "purse",
        "shortname": ":purse:",
        "channel": "people",
        "emoji_order": "1323",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["bag", "women", "fashion", "accessories", "money"]
    },
    "handbag": {
        "unicode": "1f45c",
        "unicode_alt": "",
        "code_decimal": "&#128092;",
        "name": "handbag",
        "shortname": ":handbag:",
        "channel": "people",
        "emoji_order": "1324",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["bag", "women", "fashion", "vacation", "accessories"]
    },
    "pouch": {
        "unicode": "1f45d",
        "unicode_alt": "",
        "code_decimal": "&#128093;",
        "name": "pouch",
        "shortname": ":pouch:",
        "channel": "people",
        "emoji_order": "1325",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["bag", "women", "fashion", "accessories"]
    },
    "school_satchel": {
        "unicode": "1f392",
        "unicode_alt": "",
        "code_decimal": "&#127890;",
        "name": "school satchel",
        "shortname": ":school_satchel:",
        "channel": "people",
        "emoji_order": "1327",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["bag", "fashion", "office", "vacation", "accessories"]
    },
    "mans_shoe": {
        "unicode": "1f45e",
        "unicode_alt": "",
        "code_decimal": "&#128094;",
        "name": "mans shoe",
        "shortname": ":mans_shoe:",
        "channel": "people",
        "emoji_order": "1328",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion", "shoe", "accessories"]
    },
    "athletic_shoe": {
        "unicode": "1f45f",
        "unicode_alt": "",
        "code_decimal": "&#128095;",
        "name": "athletic shoe",
        "shortname": ":athletic_shoe:",
        "channel": "people",
        "emoji_order": "1329",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion", "shoe", "accessories", "boys night"]
    },
    "high_heel": {
        "unicode": "1f460",
        "unicode_alt": "",
        "code_decimal": "&#128096;",
        "name": "high-heeled shoe",
        "shortname": ":high_heel:",
        "channel": "people",
        "emoji_order": "1330",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": [
            "women",
            "fashion",
            "shoe",
            "sexy",
            "accessories",
            "girls night"
        ]
    },
    "sandal": {
        "unicode": "1f461",
        "unicode_alt": "",
        "code_decimal": "&#128097;",
        "name": "womans sandal",
        "shortname": ":sandal:",
        "channel": "people",
        "emoji_order": "1331",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["fashion", "shoe", "accessories"]
    },
    "boot": {
        "unicode": "1f462",
        "unicode_alt": "",
        "code_decimal": "&#128098;",
        "name": "womans boots",
        "shortname": ":boot:",
        "channel": "people",
        "emoji_order": "1332",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "fashion", "shoe", "sexy", "accessories"]
    },
    "crown": {
        "unicode": "1f451",
        "unicode_alt": "",
        "code_decimal": "&#128081;",
        "name": "crown",
        "shortname": ":crown:",
        "channel": "people",
        "emoji_order": "1333",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["object", "gem", "accessories"]
    },
    "womans_hat": {
        "unicode": "1f452",
        "unicode_alt": "",
        "code_decimal": "&#128082;",
        "name": "womans hat",
        "shortname": ":womans_hat:",
        "channel": "people",
        "emoji_order": "1334",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["women", "fashion", "accessories"]
    },
    "tophat": {
        "unicode": "1f3a9",
        "unicode_alt": "",
        "code_decimal": "&#127913;",
        "name": "top hat",
        "shortname": ":tophat:",
        "channel": "people",
        "emoji_order": "1335",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["hat", "fashion", "accessories"]
    },
    "mortar_board": {
        "unicode": "1f393",
        "unicode_alt": "",
        "code_decimal": "&#127891;",
        "name": "graduation cap",
        "shortname": ":mortar_board:",
        "channel": "people",
        "emoji_order": "1336",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["hat", "office", "accessories"]
    },
    "helmet_with_cross": {
        "unicode": "26d1",
        "unicode_alt": "26d1-fe0f",
        "code_decimal": "&#9937;",
        "name": "helmet with white cross",
        "shortname": ":helmet_with_cross:",
        "channel": "people",
        "emoji_order": "1337",
        "aliases": [":helmet_with_white_cross:"],
        "aliases_ascii": [],
        "keywords": ["object", "hat", "accessories", "job"]
    },
    "lipstick": {
        "unicode": "1f484",
        "unicode_alt": "",
        "code_decimal": "&#128132;",
        "name": "lipstick",
        "shortname": ":lipstick:",
        "channel": "people",
        "emoji_order": "1339",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["object", "women", "fashion", "sexy", "lip"]
    },
    "ring": {
        "unicode": "1f48d",
        "unicode_alt": "",
        "code_decimal": "&#128141;",
        "name": "ring",
        "shortname": ":ring:",
        "channel": "people",
        "emoji_order": "1340",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["wedding", "object", "fashion", "gem", "accessories"]
    },
    "closed_umbrella": {
        "unicode": "1f302",
        "unicode_alt": "",
        "code_decimal": "&#127746;",
        "name": "closed umbrella",
        "shortname": ":closed_umbrella:",
        "channel": "people",
        "emoji_order": "1744",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["object", "sky", "rain", "accessories"]
    },
    "briefcase": {
        "unicode": "1f4bc",
        "unicode_alt": "",
        "code_decimal": "&#128188;",
        "name": "briefcase",
        "shortname": ":briefcase:",
        "channel": "people",
        "emoji_order": "1921",
        "aliases": [],
        "aliases_ascii": [],
        "keywords": ["bag", "work", "accessories", "nutcase", "job"]
    }
}
JSON;

        $result = collect(json_decode($json));

        $temp = collect();

        foreach ($result as $e) {
            $temp->push($e);
        }

        return $temp;
    }
}
